name: Cron Job
on:
  schedule:
    - cron: "25 4 * * 0"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Build
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          IAM_ACCESS_KEY: ${{ secrets.IAM_ACCESS_KEY }}
          IAM_SECRET_ACCESS_KEY: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_S3_GET_SIGNED_URL_API_END_POINT: ${{ secrets.NEXT_PUBLIC_S3_GET_SIGNED_URL_API_END_POINT }}
          NEXT_PUBLIC_S3_GET_SIGNED_URL_API_KEY: ${{ secrets.NEXT_PUBLIC_S3_GET_SIGNED_URL_API_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          node --version
          npm clean-install --progress=false
          npx next build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: travel-record
          directory: ./out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
