name: Cron Job
on:
  schedule:
    - cron: '25 4 * * 0'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Every time
        run: echo "This step will always run"
      - name: Build
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          IAM_ACCESS_KEY_ID: ${{ secrets.IAM_ACCESS_KEY_ID }}
          IAM_SECRET_ACCESS_KEY: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_S3_GET_SIGNED_URL_API_END_POINT: ${{ secrets.NEXT_PUBLIC_S3_GET_SIGNED_URL_API_END_POINT }}
          NEXT_PUBLIC_S3_GET_SIGNED_URL_API_KEY: ${{ secrets.NEXT_PUBLIC_S3_GET_SIGNED_URL_API_KEY }}
        run: |
          npm clean-install --progress=false
          npx next build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: travel-record
          directory: ./out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
