name: Cron Job
on:
  schedule:
    - cron: '15 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Every time
        run: echo "This step will always run"
